tc39/agendas

2015/07.md

...detailing proposed changes to Observable spec. Also removing topic (scarce resource disposal in generators) in apprehension of discussing it during Promise cancellation.

Adding link to Observable spec

---

2015/09.md

Seems to have been removed in https://github.com/tc39/agendas/commit/ec97e0f5922320fa98d5700ed7b85545cc7a58e3

Add class properties to agenda (again)

---

2015/11.md

I also fixed the markdown lists, which should always use "1" for easier reordering.

Add `Object.{values,entries}` + `String#{padLeft,padRight}` to agenda

---

2015/11.md

There are some consistency issues with how Symbol.species is used across the different built-ins, and there are some questions about whether new built-in constructors that support subclassing should have a species method.  Also, there is a suggestions that it might be better just to put a default Symbol.species implementation on Function.prototype.

Add agenda item for Symbol.species improvements.

---

2016/03.md

I left location/event info TBD, but wanted to get this in so we can start accepting PRs for agenda items. I took the liberty of setting the height of the Ecma logo so that it no longer obstructs the meeting details, and pulled the dates/locations of future meetings table out of the agenda items.

add March 2015 skeleton agenda

---

2016/03.md

This patch puts authors on each proposal and groups the topics into four categories. I'm making this as a PR so others can review the change first.

Reorganize and duplicate FiB

---

2016/05.md

See https://github.com/tc39/agendas/commit/e2537631585be6a193c7e02b86dcbee81a67eaf8#commitcomment-17361742.
@jeffmo

move "class field initializers" agenda item to appropriate section

---

2016/07.md

This PR adds the [Unambiguous ES Module Grammar](https://github.com/bmeck/UnambiguousJavaScriptGrammar) proposal to the July agenda.

Add Unambiguous ES Module Grammar to the July agenda.

---

2016/07.md

I'd like to present what I've learned from writing a new [transpiler](https://github.com/benjamn/reify) for ES2015 modules that does not restrict `import` declarations to the top level.
I think I can construct a convincing case for allowing nested `import` declarations, but I'm also sure I do not know all the relevant history that has gone into the current spec, which effectively restricts them to the top level.
Please have a look at the linked [document](https://github.com/benjamn/reify/blob/master/WHY_NEST_IMPORTS.md) before the July meeting (if this topic interests you), and let me know if it comes close to addressing your concerns. I'm happy to revise it or write a completely different sort of document, if folks prefer.
cc @dherman @caridy et al.

Proposal to discuss nested `import` declarations

---

2016/07.md

Since [UnambiguousJavaScriptGrammar](https://github.com/bmeck/UnambiguousJavaScriptGrammar) was just accepted as [section 5.1](https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md#51-determining-if-source-is-an-es-module) of the [Node ES6 Module Interoperability](https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md) draft proposal I'm removing this item to give us time to get our feet wet, coordinate, and prepare a discussion at the Sept. TC39 meeting.

Remove Unambiguous Module Grammar from July agenda.

---

2016/07.md

The original document had the tone of an informal sales pitch. I'm sorry if anyone read it and was bothered by that.
The pull request (and linked proposal) have been rewritten to be more appropriate for TC39, including work-in-progress changes to the specification itself.

Link to nested `import` pull request rather than sales pitch

---

template.md

@bterlson, what do you think about giving explicit (but timeboxed) priority to proposals from a previous meeting's agenda that didn't get time?

Add timeboxed overflow items from previous meeting

---

2016/09.md

- Legacy RegEx Features champion verbally confirmed 30 minutes (@erights)
- Private State champion verbally confirmed 60 minutes (@littledan)
The “Timebox Not Yet Selected” items’ champions (@msaboff, @bterlson, @littledan, @sebmarkbage) will need to either select a timebox, remove their proposal from the agenda, or move their proposal to the appropriate un-timeboxed category, ideally at least a few weeks prior to the September meeting.

Add September agenda, prepopulated with overflow items from July meeting

---

2016/09.md

I'll be attending this meeting as an invited expert, primarily to cover this topic.
The Node.js Foundation CTC along with Bradley Meck and many others have been diving deep into what it will take to implement ES Modules in Node.js. The current state of the spec, if unmodified, leaves Node.js in a position where implementing it "as is" would cause compatibility breaks with the existing module system that the Node.js project is not willing to make.
Without spec changes Node.js will be forced to implement the new ES Modules support in a way that is not entirely compatible with the spec as well as rely on out of spec behaviors like .jsm file extensions.
I'll be attending to try to represent the project consensus thus far and we are also making sure that several of the other member companies …

Node.js ecosystem compatibility breaks w/ ES Modules

---

2016/09.md

@erights @tvcutsem @bterlson 
Sorry for being late. This is what I intend to present.
* missing integrity checks for Proxies https://github.com/tc39/ecma262/pull/666, and convincing that these checks are all is needed (summary of [claudepache/es-invariants](https://github.com/claudepache/es-invariants));
* if I have time to prepare and present it: if the TargetObject of a Proxy is itself a Proxy, do the integrity checks on the TargetObject of the TargetObject;
* I don’t think I’ll have time for it: Possible solution to: https://esdiscuss.org/topic/the-invariants-of-the-essential-methods-are-false-in-case-of-reentrancy.
* ***Not included*** — and it would be great if someone else could take it: Ensure that \[\[OwnPropertyKeys]]() does not return duplicate keys, see …

+ Consolidating Proxy integrity checks

---

2017/03.md

This is about a Test262 need consensus PR, I want to limit it to 15 minutes max and preferrably not address this item during the test262 updates, which I've got a lot of other things to mention.

using root license as default for test files on test262

---

2017/05.md

> I didn't prepare any slides for this, just ideas
Feel free to comment on questions you have about the project, etc!
Some ideas after talking with @littledan (don't need to cover all):
- Babel's relevance in the JS ecosystem (npm downloads, polls, etc)
- How Babel's goals intersect with TC39: the project doesn't have an agenda for any specific proposal. We want to improve the language process for developers via earlier feedback and usage.
- Overview of Babel's implementation/architecture, go over some packages and where to contribute on each, and the ecosystem)
- proposal champions can help with implementation in JS (via a Babel plugin)
- [babel-preset-env](https://github.com/babel/babel-preset-env) and why it is important to implementers (if everyone uses Babel to compile down to ES5, …

Presentation on Babel

---

2017/05.md

Should I link to slides directly or the repo?
> https://github.com/hzoo/role-of-babel-in-js
> http://henryzoo.com/role-of-babel-in-js/
@littledan

add slides

---

2017/07.md

Adding the [export-default-from](https://github.com/tc39/proposal-export-default-from) and [export-ns-from](https://github.com/tc39/proposal-export-ns-from) to the 2017/07 agenda.

Add export-default-from and export-ns-from to 2017/07 agenda.

---

2017/09.md

This is a new (Stage 0) proposal of a feature that should improve the usability of dynamic `import()`, and whose adoption would persuade me to abandon my old [nested `import` declarations](https://github.com/tc39/ecma262/pull/646) proposal.
Please see the linked [proposal text](https://github.com/meteor/proposal-referential-destructuring/blob/master/README.md) for more information. I believe it meets the requirements for Stage 1.

Add "referential destructuring" proposal to 30min-boxed items.

---

2017/11.md

I'm presenting many topics. To encourage others to present and not hog all the time, this puts the timeboxed items where I was going to present at the bottom of their sections. Does such a change seem OK?
Addresses #271

Move my topics to the end of their sections

---

2018/01.md

I'd like to have a 30 minute time box discussion about bringing `Top Level Await` to stage 0.
I've had a combination of vacation + illness get in the way of me getting any presentation material together yet, but am confident I can have something together in time for the meeting. Please let me know if that is acceptable. If not we can push until March

Add 30 minute time slot to discuss Top Level Await

---

2018/01.md

We should probably decide on this before moving object spread to stage 4, in case a change to that proposal falls out of it (although it might not be web compatible).

Move null array spreadable to before object spread

---

2018/03.md

Imperial are hosting a "Formal Methods Meets JS" meeting the day prior to the March TC39 meeting (at the same venue), brief meeting description:
> Research talks on Programming Languages Formal Methods researchers on topics including language specification, program verification, etc. with a focus on research relating to the JavaScript language and ecosystem.
This PR adds this satellite event to the Logistics section of the agenda.

Add details of JS research meeting prior to March meeting

---

2018/03.md

This proposal was presented to the WASM CG on March 6 and has moved forward to Stage 0. It will require some small changes to the ES modules spec (to factor out cycle handling to a common base class), so I wanted to present in order to keep TC39 informed of the progress in the WASM CG.

Add update on WASM ES modules to the agenda

---

2018/03.md

Also move JS classes 1.1 to go above my hour-long presentations, partially addressing https://github.com/tc39/agendas/issues/338 .

Add more presentation slide links

---

2018/05.md

This would just be 15 seconds or so, to recap that, if you are not a delegate of an Ecma member organization, please either sign the [IP form](https://tc39.github.io/agreements/contributor/) for invited experts or remain a silent observer.
Better safe than sorry, or is this too much of a waste of time?

Add agenda item for recapping IP policy

---

2018/05.md

This is super late, so I'm not sure if it should be accepted.
If it is, it should be the lowest priority item. Maybe a time-filler if we can't get all the longer presentations items in?
And if it's not accepted, I'll do better getting it onto the next meeting's agenda on time.

Add SuperProperty evaluation order presentation

---

2018/07.md

I called into the May TC39 meeting and gave a brief overview of this proposal for Stage 0.  We are ready to advance it to Stage 2 in the July TC39 meeting in Redmond.
The summary of the proposal is here: https://github.com/sffc/proposal-unified-intl-numberformat
Please let me know if this is the correct way to add this to the agenda.
@littledan @fabalbon

Add Unified Intl.NumberFormat agenda item for stage 2

---

2018/07.md

Reordering per https://github.com/tc39/agendas/issues/397#issuecomment-398423845
- Add a "Stage 0 lightning talks" section, 10 minutes per topic
- Put discussion topics after Stage 0 lightning talks, and remaining new Stage 0 proposals after that
- Maintain the placement of overflow items at the front; we can consider changes to handle overflow buildup in a follow-on PR
Let's make sure to get feedback from the people who voiced opinions on #397 before merging. cc @leobalter @ljharb @michaelficarra @domenic

Reorder discussion topics, add lightning talks

---

2018/07.md

I'd be happy to dial in for the topic "Normative: Reduce the number of ticks in async/await", so adding my CET-related timing constraints.

Add Schedule constraint

---

2018/07.md

Thursday morning/afternoon for certain topics seems unrealistic; let's work out the details later.

Remove day/time suggestions

---

2018/09.md

It would be great to get this on the agenda to continue to move forward with the Dynamic Modules spec.
Alternatively this could be put down as a 30m item under the proposals topic updating on how this relates to the dynamic modules proposal itself.

2018.09: add PR “GetExportedNames adjustments for Dynamic Modules”

---

2018/09.md

Sorry for missing the deadline, but Ecma Fellows nominations need to be in by the end of this meeting, and we discussed the plan for this topic in the previous TC39 meeting.

2018.09: add Ecma fellows nominations

---

2018/11.md

Should this be handled all on GitHub instead? Editors, if you decide to land this patch before the meeting, no need to discuss there.

WebAssembly modules update

---

2019/01.md

I was planning to bring this up during discussion around
"Standard Library" which appears to have been removed from the agenda.
Is it too late to add this? Requesting 30 minutes but would settle for
even 5 minutes
Refs: https://github.com/tc39/proposal-javascript-standard-library/issues/12
Refs: https://github.com/nodejs/node/pull/21551

agenda: built in specifiers

---

2019/01.md
template.md

Fixes #311.
This is intended to serve mostly as a reminder, for easier cross-referencing.

meta: seeking stage 4 requires a link to the spec PR

---

2019/03.md

Angular would like to attend remotely for the decorators discussion, but due to various other events we have very limited availability during this TC39 meeting.
// fyi: @littledan

add schedule constraints for Angular

---

2019/06.md

To present an idea of how a shared namespace between the various usage scenarios of JavaScript could be managed.

Add JavaScript Commons namespace

---

2019/10.md

Sorting by timebox per requirement:
> Proposal-based agenda items should be sorted primarily by stage (descending), secondarily by timebox (ascending), and finally by insertion date.

Fix item ordering

---

2019/10.md

The new link contains exactly the same slide deck bit-for-bit, but I've hosted it in a permanent location instead of a temporary dropbox.

replace records and tuples slides link with permanent version

---

2019/12.md
template.md

ECMA402 already had a link. This adds links to the rest.
I'm not sure if this is the correct link for ECMA404. It's the best I
could find. Feel free to edit this PR before merging.

Add links to projects and CoC Committee

---

2019/12.md

According to [agenda topic rules](https://github.com/tc39/agendas/blob/master/2019/12.md#agenda-topic-rules)
> 4. Proposal-based agenda items should be sorted primarily by stage (descending), secondarily by timebox (ascending), and finally by insertion date.

Sort stage 2 proposals by timebox and insertion order

---

2020/03.md

As I said last time, I'm going to call for participants in a bi-weekly 1-hour incubation call for feedback and working-through of proposals amenable to small-group incubation. Preferably this should be done towards the end of the day when most proposals have been presented.
Aspirationally hoping to not need more than 10m.

Add incubation call chartering item

---

2020/06.md

Not sure this is the right place for the discussion, but I want to propose splitting cleanupSome from the weakrefs proposal to its own stage 3 proposal, so that we do not get blocked with weakrefs.

split out cleanupSome proposal

---

2020/06.md

Note that these are not new materials; it's just an easier overview of information that's already in the repository.

Add slides for String#replaceAll

---

2020/06.md

Fixes #782 
This meeting was due to be held in the Chicago Paypal office but it is now remote.

Clarify meeting timezone as Chicago time (UTC-5)

---

2020/06.md
template.md

Incubation calls will be re-chartered at the end of every plenary to identify the set of proposals that'll participate in the calls in between plenary meetings.

Add a recurring agenda slot for incubation call

---

2020/07.md

I'd like to propose us to flex the incubator calls to weekly meetings if we have enough topics.
Currently the incubator calls happens every other week. From my experience they are rich and help solving specific challenges for proposal before they are presented to the TC39 plenaries in a more organized fashion.
I'd like to encourage us to flex the frequency of incubator calls if we foresee enough content. If the demand is low, we can always fallback to every other week between each TC39 meeting.

Meta Discussion: Flex Incubator Calls to weekly meetings

---

2020/07.md

Adding agenda item for https://github.com/tc39/ecma262/pull/2054.

Add normative PR to next agenda.

---

2020/07.md

I'm preferring the current method semantics to a first-class type (`Range` class).
The method semantics is much JS style and provides a much clear API.
If @rbuckton is strongly requiring the first-class type please leave a comment.
In the [April meeting](https://github.com/tc39/notes/blob/master/meetings/2020-03/april-1.md#numberrange-and-bigintrange-for-stage-1) there are two kinds of ideas `iterator + non-reusable` / `first-class + reusable`, I choose the prior one. In the after discussions in https://github.com/tc39/proposal-Number.range/issues/17, I think non-reusable is a very natural idea for an iterator so I leave it as-is.
If @sffc and @littledan gonna block this due to the non-reusable semantics, please leave a comment.
----------------------------------------------
If there are …

Number/BigInt.range for Stage 2

---

2020/07.md

Ref https://github.com/tc39/proposal-numeric-separator/issues/49
I'm not gonna be able to prepare a slide or minor repo today, but I'd like to consult the desired direction from TC39. Also, it can become a small direct "PR w/ tests" package.
Short story: JSC, SpiderMonkey, and V8 and shipping w/ support for numeric separators in the exponential/fractional parts of NonOctalDecimalIntegerLiteral Literals. This conforms the current spec text of the Stage 3 NSL.
I believe this is a minor issue and I'm not sure we want to invest time to forbid this very specific case. I'm available to support a change if required, and I hope I can do it as a follow up of NSL, as we are asking Stage 4 for it in this same meeting.

Add topic for NSL follow up

---

2020/07.md

Given so many important agenda items, I'd like this discussion topic to be deprioritized, and discussed only if there's time after other items (even though it's overflow from last meeting).

Move operator overloading to the end

---

2020/11.md

The meeting was always planned to operate on Hungary local time.  Daylight savings has ended hence it is now UTC+1.

Clarify Hungary timezone

---

2021/01.md

We had some items left from the queue including one particular about identity discontinuity.
I know this agenda is packed, but I'd like to use the overflow for __a chance__ to address the remaining queue items.

Adding Realms to overflow

---

2021/03.md

This updates the TLA discussion to include the normative DFS invariant change from https://github.com/tc39/proposal-top-level-await/pull/159 based on the scenario brought up by @sokra in the example at https://github.com/tc39/proposal-top-level-await/issues/158#issue-796269657.
//cc @littledan @codehag

Include ordering invariant PR in tla discussion

---

2021/03.md

Fix table for proposals nominated to stage advancement in March meeting agenda

---

2021/03.md

This is after the currently-listed deadline, but it was listed as tomorrow until [a couple of hours ago](https://github.com/tc39/agendas/commit/ddccb43e04f7a0c79d1efccf0ec3542fd660f28e).
I've intentionally added async do out of order because it should be grouped with do expressions.

add do/async do

---

2021/04.md

This TG was presented and received consensus at the January 2021 plenary. @ecmageneva asked for us to allow additional time for representatives to weigh in outside plenary (hopefully this has been sufficient time), and the chair group was tasked with prescribing TG leadership selection processes. I would like to reserve this time to officially charter the group and to hear from the chair group about the processes that they've chosen. @tc39/chair-group would one of you be able to present for this topic?

add security TG finalisation topic

---

2021/04.md

I'd like to present on one of the following time:
- First 2hrs of any day
- If that day has Isolated Realms update, any time before it is good

Add my time constraint on 2021/04

---

2021/04.md

I know it’s generally bad form to update scheduling constraints during a meeting, but in this case it was specifically requested by the chairs, who hope to save 1 whole day for all delegates. Context: https://github.com/tc39/agendas/commit/628667e10a03f548c901e3dd9bb1351592bee8bf#commitcomment-49629723
@gesa Please let me know if this time works for y'all. Thanks so much!

Update scheduling constraint per chair request

---

2021/07.md

This intentionally points to the private repo, as per the message there.

Add Ecma proposal

---

2021/12.md

It seems like this meeting has a time overflow. And I also didn't ready to present this proposal yet. I prefer to delay it to the next meeting and communicate with other delegates about this proposal.

Delay enum proposal to next meeting

---

2022/01.md

I need to update the PR with the latest feedback and discussions, but will have that ready by end of the weekend. In the mean time I switched the PR back to draft status.

Add async iterator wrapper fix PR to 2022-01

---

2022/01.md

https://github.com/Jack-Works/proposal-enum/
Note:
This proposal (my version) has _no_ design at all.
It's intended to start with identifying the design space before actual design.
I also want to form a champion group/incubator call at the meeting. Currently I added @rickbutton and @rwaldron.

Add enum proposal for Jan 2022 meeting

---

2022/01.md

Also slightly tweak the name, since there are 2 cases where the async wrapper should close the iterator

Add slides to async wrapper close

---

2022/03.md

Ref https://github.com/tc39/proposal-shadowrealm/pull/348
In the TC39 Dec 2021 plenary we got consensus to set `name` and `length` for Wrapped Exotic functions within the ShadowRealms proposal. Even though, the meeting notes ended somehow ambiguous about the `name` property being prefixed with "wrapped " or not. The intention from the champions - as presented in that plenary - was to not use the prefix.

Add ShadowRealms clarification entry

---

2022/03.md

Sorry for the hurry to add a new agenda item! This is not a new proposal (or at least not intended to take stage advancement).
[New integrity level](https://github.com/tc39/proposal-limited-arraybuffer/issues/15), a try to unify [limited array buffer](https://github.com/tc39/proposal-limited-arraybuffer) and [read only collection](https://github.com/tc39/proposal-readonly-collections) proposal. ([slides](https://docs.google.com/presentation/d/1H0_eShe6JW0iKwHrG_TjdYRyrlGJF58g8rYt65bWiS0/edit?usp=sharing))
Discussed with @erights and we want to talk about this at the meeting.

Add New Integrity level discussion

---

template.md

We wish to ensure the chairs can prepare the schedule ahead of time to cater for the needs of delegates working on different timezones.
cc @ryzokuken

Add 48 hour preference for notifying of schedule constraints

---

2022/06.md

I don't think we had sufficient time to discuss the proposal in the October, 2021 meeting. I'm increasing the expected timebox to account for discussion time.

Increasing timebox for Atomic Operators

---

2022/06.md

Not strictly necessary for Stage 1, but worth including for reference.

Adds Draft spec link for RegExp Atomic Operators

---

2022/07.md

Current throws `Uncaught RangeError: invalid ISO 8601 string: 2022-07-19:00[America/Los_Angeles]`

Fix malformed ISO date in 2022-07 agenda

---

2022/07.md

This is after the advancement deadline, so I'm doing this by PR in the hopes it gets more visibility that way.

links slides for "avoid mostly-redundant await in async `yield*`"

---

2022/11.md

Part of the discussion will probably apply to both proposals, so I would like to have them one after the other. I was considering putting them under a single agenda item, but since:
- they are at different stages
- one is a status update, the other one is asking for advancement
I ended up using two topics with a schedule constraint that I would like to have them together. It's not exactly how schedule constraint are meant to be used: is it ok?
Also I moved the Module/ModuleSource proposal to the correct position in the table, since it's not at Stage 2 yet (cc @kriskowal / @caridy)

Add module expressions&declarations

---

2022/11.md

As far as I understand, all constraints should go either in the "Normal constraints" or in the "Late-breaking schedule constraints" sections.
It's important that they are properly sorted, because as the comment in the agenda says "Conflicting constraints honored on a first-come, first served basis". This PR sorts them in the same order as they were committed.

2022.11: Move schedule constraints to the correct sub-section

---

2022/11.md

This change corresponds to https://github.com/tc39/agendas/pull/1291, but updates the dates listed at the end of last meeting's agenda, which I sometimes refer to.

update January meeting dates

---

2023/01.md

https://github.com/tc39/agendas/pull/1291 probably should have included this, but even before then it was off by 10 - I'm guessing a typo?

fix date in temporal snippet

---

2023/01.md

Also removes the TBD slides for the `context.access` topic, will directly discuss linked issue instead.

Add slides for Async Resource Management

---

2023/01.md

There seems to be enough time remaining in the agenda that this shouldn't overflow to the next meeting, but I want to make sure that this has high enough priority to be discussed this meeting if the schedule shifts.

Add scheduling constraint for "Decorator `context.access` object API"

---

2023/01.md

Given the discussion in https://github.com/tc39/proposal-decorators/issues/69, this topic is something we really need to discuss for the January meeting, since it will inform what we ship in TypeScript 5.0 RC.

Add topic for decorator/export ordering for January 2023 meeting.

---

README.md

We only do two-month-ahead surveys to confirm hybrid meetings.  Remote meetings can be considered to be solid.  So I am marking the remote meetings as confirmed.

Confirm meetings

---

2023/03.md

The "Slides" content is already in a comprehensive [readme](https://github.com/justingrant/proposal-canonical-tz#handling-time-zone-canonicalization-changes). I'll summarize into simpler slideware before the meeting.  In the meantime I linked to the readme.

Handling Time Zone Canonicalization Changes for Stage 1

---

2023/03.md

Adds an agenda item for an update on the type annotations proposal (no stage advancement requested) plus a schedule constraint.

Add type annotations update to agenda & schedule constraints

---

2023/03.md

Add slides link so reviewers won't have to read as much vs. the previous longform writeup.
Same content, just shorter. 
Also shortened the name of the proposal because I got feedback that the old name was a mouthful.

Add slides link for Time Zone Canonicalization proposal

---

2023/05.md

This proposal only has only ~10 lines of normative spec changes, plus one editorial paragraph. I wasn't sure of the best way to communicate these spec changes for Stage 2. As a starting point I screenshotted the changes into slides and linked my "spec" link in this PR to those slides. 
I could also link to the (small) spec HTML file.  But the slides are probably the easiest way to review the changes, so that's what I linked to in this agenda PR. If that's not correct, let me know!

Add Time Zone Canonicalization proposal for Stage 2

---

2023/07.md

The wrong date was on the agenda.

Fix typo in Temporal code sample

---

template.md

`necessary materials` is ambiguous and undefined.  this change normalizes the text to `supporting materials` which is the correct term used throughout and is defined

📝 necessary -> supporting

---

2023/11.md

https://app.element.io/#/room/#jsx:matrix.org

Add call for JSX

---

2023/11.md
template.md

If we have the "normal constraints" section we should use it

Add note to put schedule constraints in the relevant section

---

2023/11.md

Hi everyone, TCQ is alive and kicking:
Forgive us childish test data. Sometimes we even might grow up.
We would like to present our efforts on getting TCQ up and running and how to continue its evolution. For the curious have a look at https://github.com/zalari/tcq , although that spoil things quite a bit...

Add presentation on TCQ reloaded

---

2024/04.md

Updates the agenda item for the ESM source phase to also include the new layering update in https://github.com/tc39/proposal-source-phase-imports/pull/62. There is a very close conceptual relation here, so having it in the same agenda item works out.

Add layering PR along with ESM source phase update

---

2024/06.md

Add agenda item for:
Normative: specify time zone ID requirements to reduce divergence between engines https://github.com/tc39/ecma402/pull/877

Add needs-consensus PR item for ECMA-402 #877

---

2024/06.md

Invited by Luca and Dan E, a talk on an experimental engine interpreting the ECMAScript specification in a data-oriented way; the intention is to motivate and encourage new ways to look at the language.
The talk was given at Web Engines Hackfest and received a fair bit of interest and spawned this invitation to take the talk to TC39. The talk is approximately 25 minutes in length, though at WEHF the QA after took it to 37 minutes in total length. I was instructed to open a pull request to add the talk to the agenda to get the talk scheduled.
On the actual scheduling side, Wednesday 19th would work the best for me but any day is doable.

Propose / schedule Nova engine talk

---

2024/07.md

Previous versions of the spec failed to account for the possibility that negative durations could start with zero-valued hours or minutes values.

add Intl.DurationFormat: Display negative sign on leading numeric-style zeroes

---

2024/10.md

I was hoping for this to be a quick update but unfortunately we found a bigger problem and I need committee input on which direction to take.

2024.10: Add import defer slides, extend timebox, update constraints

---

2024/10.md

Hosts have agreed to go longer on Thursday to accommodate a packed agenda.

Extend Thursday to 5pm

---

2024/12.md

Immutable ArrayBuffers for stage 2
Stabilize for stage 1 with links coming
Schedule constraints: I will likely miss Monday

2 proposals + schedule constraints

---

2024/12.md

Don't have slides yet, but wanted to add this timebox.
We can also do this in a separate session if the TG1 agenda fills up too much.
CC @ben-allen @nicolo-ribaudo @jessealama @ljharb

Add "Vision for numeric types in ECMAScript" to 2024-12 agenda

---

2024/12.md

I'd like to request larger timebox so we can look at a design question (https://github.com/tc39/proposal-upsert/issues/40) during committee.

Increase upsert timebox

---

2024/12.md

This is an entirely editorial PR with one commit mismarked as normative. Does not need plenary approval.

Remove spurious DurationFormat PR, as it was an entirely editorial PR

---

2024/12.md

Apologies for adding these slides so late — they don't require any concrete feedback and they are not proposing anything normative. I mostly added the topic since I saw that the agenda had a lot of free time.
@tc39/chairs I added a scheduling _preference_ for it, but if the schedule is already done then it's fine.
cc @guybedford

2024.12 Add "Module harmony" slides

---

2025/02.md

meeting date in js code should be `2025-02-18`, not `2025-12-18`

Fix typo in meeting times in 02.md

---

2024/10.md
2024/12.md
2025/02.md
template.md

Lets see if this works -- I'm not sure about how GitHub caches images.
Server code (using temporal and iterator helpers 😄): https://dash.deno.com/playground/tc39-agenda-time
```js
const pattern = new URLPattern({ pathname: "/:year/:month{/}?" });
Deno.serve(async (req: Request) => {
try {
const { year, month } = pattern.exec(req.url).pathname.groups;
const res = await fetch(`https://raw.githubusercontent.com/tc39/agendas/refs/heads/main/${year}/${month}.md`);
const body = await res.text();
let outputText;
if (res.status === 404) {
outputText = "Err 404"
} else if (!res.ok) {
return new Response("Error while fetching the agenda:\n\n" + body, {
status: res.status,
headers: { "content-type": "text/plain" }
});
} else {
const minutes = body.matchAll(/\b(\d+)m(?=\s*[,|)])(?!\) Timeboxed …
```

Experiment: Add total duration to the agenda

---

2025/02.md

"Proposals looking to advance to stage 4 must link to a pull request into [the spec](https://github.com/tc39/ecma262), since the [process](https://tc39.github.io/process-document/) requires one."
(In both cases you can find the spec PR by following a link from the linked issues, but I have always understood the requirement to link to supporting materials to mean that you must _directly_ link to them.)

add links to spec PRs for going-for-stage-4 proposals

---

2025/02.md

I was planning on not having slides and just linking to the tests (since there are no changes to the proposal), but I got feedback that slides still are nice to have something to look at rather than screen-sharing GitHub :)

2025.02: Add import defer slides

---

2025/04.md

The start date should be April 14?

Fix the date

---

2025/05.md

Please note that the proposal-array-from-async proposal is out of date and still has a pending pull request (tc39/proposal-array-from-async#50). 
The most up-to-date version is the tc39/ecma262#3581 pull request linked in the table.

2025-05: add Array.fromAsync Stage 4 and BigInt Math Stage 2

---

2025/05.md

There won't be time to fully merge the upsert tests from staging, I'll plan to present this item at the next plenary.

2025.05: remove upsert

---

2025/07.md

I also noticed that the Import Buffer item appears to have been added in the wrong place in the agenda, but didn't touch it.

2025.07: Add keep-trailing-zeros slides and add Amount for Stage 2

---

2025/09.md

Bit late but since this is only documenting an existing convention I hope it's OK.

add item for strings-as-enums are kebab-case
