2015/01.md

I wanted to discuss three final items about `@@toStringTag` - a wiki with more detail is linked.

Last-minute `@@toStringTag` discussion

---

2015/01.md

The Paris location has been confirmed for the March meeting.

Location for March meeting

---

2015/01.md

Updating per https://esdiscuss.org/topic/tostringtag-spoofing-for-null-and-undefined

Tweak @@toStringTag agenda items based on es-discuss discussion

---

2015/03.md

Adds a link to the [in-progress] gist I'm working on for the ES7 Class Properties proposal

Add link to gist for ES7 class properties proposal

---

2015/03.md

A new proposal for ES7 immutable value types.

Adding Immutable Data Structures Proposal

---

2015/03.md

Last minute add if we have a bit of time.

Add export __ from to agenda

---

2015/07.md

My agenda topics for next week.

Rest/Spread Properties Bump + trimLeft/trimRight

---

2015/05.md

Adding link to my observable presentation.

Adding the observable presentation

---

2015/11.md

transplanted some info from the last meeting notes -> https://github.com/tc39/agendas/blob/master/2015/09.md

November Agenda Dates/Location (Extracted from latest meeting notes)

---

2015/11.md

Adding Observable proposal to agenda (stage 2)

Adding Observable proposal to agenda

---

2015/11.md

Hopefully we'll have time for these :-) no worries if not.

Add `Error.isError` and `System.global` to agenda

---

2016/01.md

* dinner location
* notice about street closures around the salesforce office

details about next meeting

---

2016/01.md

Also cross out completed items.

Add Object.getOwnPropertyDescriptors

---

2016/01.md

Fix markdown

---

2016/03.md

add "Lifting TemplateCharacter Restrictions" proposal

---

2016/03.md

Would like to give an update on the status of public class fields if there's time

Add public class fields to agenda

---

2016/05.md

Not sure if it makes sense to put this on the agenda, as it is unofficial, so leaving this as a PR. WDYT?

Community reception

---

2016/05.md

test262: Definitive decision for Test262 console runner

---

2016/05.md

Add to agenda

---

template.md

Thought I'd add an agenda template with some of the changes discussed during and after the last meeting. This is merely a first stab, feel free to tear it apart.

Add agenda template

---

2016/07.md

Moving stage 0 to 1 proposal to timeboxed list and adding PR

Update items for Leo Balter

---

2016/09.md

Champions: @littledan @bterlson

Add RegExp Unicode property escapes proposal to September agenda

---

2016/09.md

Add RegExp `s`/`dotAll` flag proposal to September agenda

---

2016/09.md

Update venue and contact information.

Update agenda for Sept 2016 meeting.

---

2016/09.md

Proposal to dis-ambiguous Module and Script goals.

Add UnambiguousJS to September agenda

---

2016/09.md

ref tc39/ecma262#689
cc @bterlson :)

Add arguments.caller removal

---

2017/01.md

Add agenda item about stage-1 null prop operator.

---

2017/01.md

Ref c7796e0d43d3e8f6afd5cd01b570b40267190219 (see the comments)
My point is to defer to other CoCs only if this one is rejected.
I'm also time-boxing this so if we can't reach consensus before 30 minutes I will consider other forms.

Use the Covenant CoC only

---

2017/05.md

Adding under 30 minutes time slot.

Adding numeric separators to the agenda

---

2017/07.md

now actually does it for real :)

moves to the 30 minute slots as originally intended

---

2017/09.md

Hoping to advance the `Builtins.typeOf()` and `Builtins.is()` proposal
Ping @ljharb

Add `Builtins.typeOf()` proposal

---

2017/09.md

Added an agenda item for Throw Expressions, and links to slides for other topics.

Add agenda item for throw expressions

---

2017/09.md

I republished my slides to Google Docs to make it easier to present, and have updated the links to the slides below.

Updated links to slides

---

2017/09.md

Apply the Herman Normalization algorithm

---

2017/11.md
template.md

Per discussion on https://github.com/tc39/agendas/commit/950e2410cf3d60eebc367f986b4b9b70dd669f7b, and in the 2017.09.28 TC39 meeting.
Closes #258.

Clarify hourglass rules

---

2017/09.md
2017/11.md
template.md

The only item that seems like it maybe could have some discussion is moving the "needs consensus" PRs up to the top, and adding the timebox sections to them.
I'll plan to merge this in a day or so if there's no objections.

Update with Rex’s suggested changes

---

2017/11.md

Signing up to give a quick presentation on vulnerabilities in Array[@@species] and Array index accessors
@ajklein

Array Security Presentation

---

2017/11.md

@mathiasbynens, @ajklein: WDYT? I'm not really sure this deserves 60 minutes of folks' time, and I'd be fine with timeboxing it to something smaller. Y'all know the group (much) better than I do, so I'd appreciate your advice. :)

Add string literal distinction to the agenda.

---

2017/11.md

Following discussion in https://github.com/tc39/agendas/pull/280

Cover "stage 4 requirements" on the first day after noon

---

2018/01.md

I'm working on a description & slides for the proposal, and will add the links later.

Add Maximally minimal mixins proposal agenda item

---

2018/01.md

I wanted to add an open discussion about how we can get the community more involved in TC39.
Slides to come, this is not a proposal looking for advancement

add tc39 and community presentation

---

2018/01.md

Add 30 minute time boxed slot for presenting new set builtin methods

---

2018/01.md

chore: fix indent of 30 minute Jan 18 items

---

2018/01.md

I hope to produce slides on this - but the slides will simply be the explainer README, in a more presentable format.

add "proposal-array-last" to 30 minute agenda items

---

2018/01.md

Was hoping to get the slides completed for the deadline; I'll PR later - before the meeting - for links to the slides

add operator overloading, multi module files for stage 1

---

2018/01.md

This PR likely needs more discussion than what the timebox for the other needs-consensus PRs allows for.

Add needs-consensus PR

---

2018/05.md

Per [Entrance Criteria](https://tc39.github.io/process-document/) for Stage 1:

Add Module Keys Stage 0 Strawman to agenda

---

2018/05.md

Per discussion with @littledan in https://github.com/tc39/agendas/pull/323

Request a 30 minute slot for Module Keys proposal up from 15 minutes

---

2018/03.md

I'm still working on filling everything out on my GitHub README.md but it's workable rough draft.

Add module fallback imports to the agenda.

---

2018/03.md

And split out excess detail to new document.
(Pull request is to ensure people get notifications of this large, quite late change)

Add Local Information for March Meeting

---

2018/03.md

And Salesforce time constraints

Add transpilers slides for discussion

---

2018/03.md

Await in parameter defaults for non-arrow async functions

---

2018/05.md

Add PR 1144

---

2018/05.md

https://github.com/tc39/ecma262/pull/1174

Add `export * as ns from "mod”` PR

---

2018/05.md

Code of Conduct reminder

---

2018/05.md

Timeboxed updates from the CoC committee

---

2018/05.md

Hopefully I'll have another one coming soon.

add agenda items from Michael

---

2018/05.md

ah whatever why not, let's put this up there too :) That's three!
Will I be cool like @littledan after this?

add agenda item for collection literals

---

2018/05.md

Add Symbol.thenable to agenda

---

2018/05.md

Adds time for the following proposals:
- RegExp Match array offsets for Stage 1 (Ron Buckton) ([explainer](https://github.com/rbuckton/proposal-regexp-match-offsets#readme)) 
- Class Static Block for Stage 1 (Ron Buckton) ([explainer](https://github.com/rbuckton/proposal-class-static-block#readme)) 
- Class Access Expressions for Stage 1 (Ron Buckton) ([explainer](https://github.com/rbuckton/proposal-class-access-expressions#readme)) 
- Explicit Resource Management for Stage 1 (Ron Buckton) ([explainer](https://github.com/rbuckton/proposal-using-statement#readme)) 
- Enums for Stage 1 (Ron Buckton) ([explainer](https://github.com/rbuckton/proposal-enum#readme))

Adds several Stage 1 proposals to the agenda

---

2018/05.md

Put this in "non-timeboxed" to deprioritize
This is after the deadline, but not looking for stage advancement or adding more timebox time.

Breaking up discussion into two topics

---

2018/05.md

None of these slides contain (or will contain) any new material that was not already part of the respective repositories per the deadline. They just summarize the already available info in an easier-to-present way.

Add slide links

---

2018/05.md

Thought I sent this earlier, my apologies

Add slides for Top-Level Await

---

2018/05.md

Make Realms for Stage 2 be another item (there is no line break right now)

Fix 30-minute items sublist

---

2018/05.md

fixes #385: document agreed-upon time slots for agenda items

---

2018/05.md

Swap two timebox lengths

---

2018/05.md

Postponing enum proposal to a later meeting to further discuss and reframe presentation.

Postpone Enum proposal

---

2018/07.md

And sorting the new discussion topic under the overflow topics from last meeting

Decorators for Stage 3

---

2018/07.md

Seems to have been copied over from the previous meeting by accident

Remove Istvan schedule constraint

---

2018/07.md

Will provide an update soon with the presenter once I've got this confirmed.

Include Dynamic Modules Proposal

---

2018/07.md

Appreciated for flexibility here while I got this confirmed.

Update Dynamic Modules presenter

---

2018/07.md

Fixed the date of the meeting at GoDaddy. Date was specified as 2018.

Fix date of future meeting

---

2018/07.md

Update link to resource management slides

---

2018/07.md

Slides contain content from proposal's README file, but in presentation format.

Slides for Intl.NumberFormat proposal

---

2018/09.md

Ad-hoc history group - short presentation

Add agenda item from Allen Jory & Istvan

---

2018/09.md

A typo introduced by https://github.com/tc39/agendas/pull/441

add missing parenthesis

---

2018/09.md

Replace my name with Kevin Smith for a Normative proposal after offline discussion, as he presented the same change on the last meeting.

Remove my name from agenda

---

2018/09.md

Deferring class static block until a later meeting.

Defer class static block

---

2018/11.md

Adding my proposal for Optional Chaining stage advancement for November

Adding to proposal presentations for November

---

2018/11.md

And, possibly delaying value types introduction
(depends whether I have time before the meeting; happy to chat about the topic with anyone who's interested)

Decorators Stage 2 status update

---

2018/11.md

Let's see if there's interest in pursuing something in this space. Whether it is syntax or something on `import.meta`.

Add item about Asset References to Agenda

---

2018/11.md

Hashbang grammar proposal is breaking the order

Sort proposals in November agenda by stage

---

2018/11.md

this is more like a placeholder as I believe other Bocoupers might present this one.

Test262.report

---

2018/11.md

Just to note here explicitly that this item would need to be scheduled for the morning for me to make it with timezone constraints.

Note scheduling constraints for #1306 discussion

---

2019/01.md

I believe I'll be remote, but I'm happy to present. :smile:

Add my Needs Consensus PR to the January agenda.

---

2019/01.md

Add Private Declarations

---

2019/01.md

While I'm not championing the proposal, I first confirmed with Jordan Harband (@ljharb) it's ok to present this to the committee. My goal is to give a last try advocating for `Global` regarding the extensive community feedback we received from developers and educators.

Add entry for globalThis proposal

---

2019/01.md

@Ginden is it true that you will be presenting this topic with @gsathya at the upcoming meeting?

fix @ginden's name

---

2019/01.md

It would be great to follow up on the previous meeting on the current status, and to get provisional approval on the layering approach.
//cc @ljharb @bmeck

Add dynamic modules agenda item

---

2019/01.md

agenda: replace github link with slide deck

---

2019/03.md

Added details and references to [reflector](https://github.com/tc39/Reflector/issues/210
) issue

doc: add details for march meeting

---

2019/03.md

https://github.com/tc39/ecma262/pull/1407

Discuss string representation of negative years (needs consensus)

---

2019/03.md

If anyone wants to block advancement due to missing the deadline, so be it.

Add Promise.allSettled for stage 3

---

2019/03.md

Time constraints, Ecma402 updates, etc

Updates for the Agenda

---

2019/03.md

There's ongoing work from @annevk in HTML in this area; I'd like to see how that's concluded before pushing forward this layering change.

Remove job queue topic

---

2019/03.md

cc @gsathya, @ajklein, @erights, @dtribble

Add WeakRef update to the agenda

---

2019/03.md

Add slides for WeakRefs topic

---

2019/06.md

Slides for JavaScript Standard Library agenda item.

Add link to slides for JSL

---

2019/06.md

Add Domenic and Anne schedule constraints

---

2019/06.md

Add Promise.any

---

2019/07.md

Add agenda item for Infix Bang.

Add Infix Bang to July 2019 Agenda

---

2019/07.md

@leobalter @ljharb I made some slides.  I think it is worth discussing this topic with TC39.  Thoughts?

Add casing to open-ended discussions

---

2019/10.md

Schedule Temporal for update and potential advancement (if we can get minor issues ironed out by the deadline)

Schedule Temporal

---

2019/10.md

I'd just like to avoid Thursday afternoon
cc. @robpalme

Add my own availability to present const value types

---

2019/10.md

Add ECMA-402 casing conventions to October agenda

---

2019/10.md

The previously linked PR is now closed

Update link for TLA status update

---

2019/10.md

I'm traveling on Tuesday and managing an event on Wednesday.

chore: add schedule constraint

---

2019/10.md

I'd like to defer this by one meeting (to December) so that I can present in person.

Removing class features updates from agenda

---

2019/10.md

We are changing the name of the proposal but there is no substantial change to the proposal itself.
cc. @robpalme @littledan

Change the name of Const Value types to Records and Tuples

---

2019/10.md

Sorry about the second PR, I forgot to add the slides with the last one

Add the slides for Records and Tuples

---

2019/10.md

Hiya folks --
Please find my scheduling constraints in this PR. I'm presenting remotely from Pacific timezone, so mornings don't really work well for me. I'm in IRC as `decompiled` if you need to reach me or feel free to comment here.

Time constraints for Object.map proposal

---

2019/10.md

Remove Emitter status update agenda item

---

2019/10.md

update link to slides based on proposal.

chore: link to slides rather than proposal

---

2019/12.md
README.md

Appreciate if someone can take a look and give me thumbs up.

Agenda December 2019 (Salesforce hosting)

---

2019/12.md
template.md

Update template with appropriate public info

---

2019/12.md

Just a simple idea from an IRC chat, to see if anyone else likes it.

Add Array select/reject

---

2019/12.md

Planning to present this. Thinking 15 minutes should be sufficient, please lmk if you think we need 30

doc: import meta for stage 4 Dec 19' meeting

---

2019/12.md

add a quick UUID update to the agenda, we are not asking for advancement.

chore: add UUID update to agenda

---

2019/12.md

The SpiderMonkey implementation hasn't landed due to some concerns still to investigate.

Removing Intl.Locale for Stage 4

---

2019/12.md

/cc @mikesamuel @bakkot 
Please follow the agenda ordering rules next time.

fix proposal item ordering

---

2019/12.md

https://docs.google.com/presentation/d/1FV_wOYUgmoYpxb6yCjuQDH50ne0lFqhH52Mfwdh5Lio/edit#slide=id.p

Operator overloading slides

---

2019/12.md

Have not had time to work on this, will aim to do it at next meeting.

remove import.meta stage advancement from agenda

---

2019/12.md

I will only be able to attend in person on one day, and was thinking Wednesday might be best :smile:
Let me know if this constraint is a problem :+1:

constraint: request that Ben present on Wednesday

---

2019/12.md

Presentation materials are not going to be ready in time for this meeting. /cc @devsnek

remove iterator helpers from December agenda

---

2019/12.md

If this is too long I would rather do a 10mn demo than nothing.

Extend jsexplain demo to 30mn

---

2019/12.md

Sven has a schedule constraint

Sven and Dan Clark on module attributes

---

2019/12.md

https://docs.google.com/presentation/d/1pyRtuOjnaTV_wr3a7sOZEt3PVxrbhgy_JCXovm0Dklk/edit#slide=id.p

Module attributes slides

---

2019/12.md

I'll appreciate review for this PR; not positive if these need overflow discussion

Check off items that we covered

---

2020/02.md

Proposal links and slides will be added later.

Add extension proposal for stage 1

---

2020/02.md

Sorry for this being past the agenda item. Chairs, please feel free to deprioritize these items.

Two late topic additions

---

2020/02.md

I would like this discussion to pre-empt any technical topics, as proposed changes (if accepted) would apply during this meeting. I may be able to get a few slides later this week or this weekend.
/cc @tc39/chair-group If you're available for a call before the meeting, I can brief you on the proposal and possibly align with any plans you already have. @MylesBorins is already pretty familiar with the proposal.

process changes to accommodate US members and US delegates

---

2020/02.md

As discussed in https://github.com/tc39/proposal-intl-segmenter/issues/97#issuecomment-581378290

Not proposing Intl.Segmenter for Stage 3 yet

---

2020/02.md

I've moved the content of the gist into a full git repo.

Updating link for ArrayBuffer.fillRandom

---

2020/02.md

Didn't have enough energy and time to write all details in past week due to health reason. Postpone to next f2f meeting.

Remove static extensions proposal from agenda

---

2020/03.md

apologies, I directly commited to master on the first attempt.

Add Record and Tuple update to 03/2020 agenda

---

2020/03.md

New agenda item:  'OptionalChain'.PrivateIdentifier as valid syntax

---

2020/03.md

I'd like to ask for 30 min, if possible because I think it is very likely that discussion of this PR can last more than 15 min based on this [thread](https://github.com/tc39/proposal-class-fields/issues/302).

Ask for 30 min timebox on agenda item

---

2020/03.md

CC @leobalter @spectranaut @littledan @zbraniecki @nciric

Add Intl.NumberFormat V3 for Stage 1

---

2020/03.md

This is to discuss the format of Remote Plenaries going forwards.

Add Remote Plenaries agenda item

---

2020/03.md

Last meeting we introduced a number of changes and promised to have a
follow up discussion in the following two meetings. This is an open
ended conversation to review how things are going, gather feedback,
and determine if next steps are required.

2020.03 Discuss process changes to accommodate us delegates

---

2020/03.md

I think the original title was perhaps not descriptive enough. Thoughts?

2020.03 Improve description of process discussion

---

2020/03.md

2020.03 Add slides for secretariat report

---

2020/03.md

It occurred to me that this probably requires explaining enough background to warrant an actual presentation rather than just speaking ex tempore.

Add slides for PR 1869

---

2020/03.md

Apologies for originally submitting it in a comment instead of here in the first place, I hadn't realized what the procedure was.

Add schedule constraint for Temporal presenters

---

template.md

[WIP] update agenda template; fixes #722

---

2020/03.md

2020.03 add slides for remote plenary

---

2020/03.md

We have this on tcq and hackmd, but missed it on this agenda

2020.03 Add agenda item for 2020 spec vote

---

2020/06.md

I messed up the order of the markdown table...  whoops.

Fix needs consensus PR agenda items table.

---

2020/03.md

Add slides for discussion of process changes we implemented last meeting

2020.03 process changes slides

---

2020/06.md

Based on prior conversation
Thoughts?

Update schedule for 4 day 5 hour sessions.

---

2020/06.md

Possibly Stage 3, but time can be reused for updates if not ready for stage advancement.
cc @caridy

Adding Realms (2020-06)

---

2020/06.md

No request for stage advancement at this meeting.

Realms will just have Stage 2 updates this meeting

---

2020/06.md

The update of the proposal in this [pull request](https://github.com/tc39/proposal-intl-duration-format/pull/12)

Add a slot for intl duration format proposal

---

2020/06.md

This is a placeholder for now, waiting on Shu's ok for adding this...

add sublcassing removal proposal

---

2020/06.md

@syg, we could also just merge our items into one big “update” topic where we discuss the open PRs for this proposal, WDYT?

Add Promise.any & AggregateError update

---

2020/06.md

@syg @michaelficarra does this work for y'all?

Add schedule constraints

---

2020/06.md

Add slides, and scheduling constraints

Update Decorators agenda item

---

2020/06.md

And update future meeting details to match.

Add slides for meeting schedule

---

2020/07.md

Add tc39/ecma402#471, normative PR to fix awkward rounding behavior in `Intl.NumerFormat`.

Add "Handle awkward rounding behavior"

---

2020/07.md

Just realized I've had this sitting open on my desktop since Friday and forgot to hit the "Create pull request" button :(.

Add class static block to agenda

---

2020/07.md

I don't know if 45m will be required, but I want to give enough space and opportunity for discussion & brainstorming additional ideas.

Add 45m time slot for Examining structural racism

---

2020/07.md

Forgot this originally; hopefully making it easier to review the agenda

Add link to Temporal repo

---

2020/09.md

`String.dedent` Stage-1 proposal.

String.dedent Stage-1 proposal.

---

2020/09.md

Add temporal stage 2 update

---

2020/09.md

Skipping operator overloading topic this meeting

Class features and outreach groups

---

2020/09.md

cc @gesa @bterlson @MylesBorins

Add future meeting

---

2020/09.md

This is a "short timeboxed discussion", I believe

Add GetOption in ECMA-262 discussion

---

2020/09.md

As I'm stepping away from the maintenance of Test262, I'd like to celebrate this with an overview of the last 5 years I've been in contact with this project. This should also include how I should still be involved with it.

Add open-ended discussion about Test262

---

2020/09.md

Not seeking stage advancement, but apologies for the lateness

Add a late agenda item to discuss MDN and TC39

---

2020/09.md

Update schedule constraints

---

2020/09.md

Add class features slides

---

2020/11.md

Fix timezone for advancement deadline

---

2020/11.md

That's a tentative. I'm doing some final syncs but it seems we have a good perspective for request a stage 3 advancement in this meeting.

Add Realms for Stage 3

---

2020/11.md

Realms are currently on stage 2
cc @leobalter

fix proposals sorting

---

2020/11.md
template.md

The how-we-work article is more descriptive

Link to how-we-work rather than Allen's paper

---

2021/01.md

Fix invalid link

---

2021/01.md

Adding topic to agenda pending completion of stage 3 reviews.

Class static init. blocks for stage 3 (tentative)

---

2021/01.md

Tentatively adds RegExp Match Indices for stage 4 to the agenda.

Add RegExp Match Indices to Agenda

---

2021/01.md

cc @davethegr8 @jasonwilliams @littledan for co-presenters, who wants in?

Add timeslot for Inclusion WG updates

---

2021/01.md

This is going to be my first week working at Slack, so my scheduling is very up in the air at the moment, but I definitely won't be available on Monday.

Add my scheduling constraints

---

2021/03.md

Seems only a few works todo. I have nearly finished the spec.
I think we could push it into stage 2 after finished the spec review.

Add find from right for stage 2

---

2021/03.md

https://github.com/tc39/ecma262/pull/1867 arguably has consensus, but I'd like to revisit it briefly to reaffirm before landing.

add tc39/ecma262#1867 for march

---

2021/03.md

CC @mathiasbynens @markusicu @macchiati @aheninger

Add Stage 1 update for Unicode set notation in regular expressions

---

2021/03.md

Editors recommended us to increase the timebox for Temporal. If possible, we'd like to reserve one hour on each of the two days.

Increase Temporal timebox

---

2021/03.md

ref. discussion on https://github.com/tc39/agendas/commit/8dbf4c8b81ca6309d0155041addfff2c18efcb99
also: add myself as presenter

Move Temporal back out of long discussions section

---

2021/03.md

optimal time given Wu's timezone

updating constraints for error-cause

---

2021/04.md

Add agenda item for Object.has for April 2021 meeting

---

2021/04.md

Note: Slides & Presenter are tbd, do we want to wait to merge this PR until they are finalized?

Request to add NVC Training Proposal to agenda

---

2021/04.md

NOT for advancement , need to ask for Stage 3 reviewers sign up.

Add "Update link of Intl Enumeration API Stage 2"

---

2021/04.md

Normative changes on which Stage 3 was conditional, have been resolved. Just an announcement, no timebox necessary

Short announcement on Temporal Stage 3 conditional

---

2021/04.md

Scheduling constraint: unavailable wednesday

Add pattern matching to 2021-04 agenda

---

2021/05.md

Slides are still WIP but the content should already reflect most of what we want to present and discuss

Add slides for Realms

---

2021/05.md

I was advised that 15 minutes is the standard for a very short item and that it's better to overestimate than underestimate.

Adjust timebox and add hourglass

---

2021/05.md

Rick, Caridy, and I have an internal meeting on Wednesday we need to prioritize, I'm sorry for such a short notice.

New constraint

---

2021/05.md

Draft spec in Google doc; linked from slides but here is a direct link.

direct link to draft spec for RegExp set+strings

---

2021/05.md

Add ECMA-402 Editor's slides

---

2021/05.md

@leobalter explains @littledan and @caiolima no longer have this constraint

Removing schedule constraint for Dan/Caio

---

2021/07.md

https://github.com/tc39/ecma262/pull/2360

Add ecma262#2360

---

2021/07.md

Slides TBD for this specific meeting. For the records, link to the [last slides is here](https://docs.google.com/presentation/d/1c-7nsjAUkdWYie5n1NlEr7_FxMXHyXjRFzsReLTm8S8/edit#slide=id.gd9d6e4cbad_0_59)

Add Realms to 2021-07

---

2021/07.md

Add TG3 Chair election

---

2021/07.md

Also schedule constraints
See https://github.com/tc39/proposal-temporal/issues/1583#issuecomment-877506169

Add late timeboxed discussion item

---

2021/08.md

Slides to follow before deadline

2021.08: add change-array-by-copy

---

2021/08.md

Since it’s the first time I’m championing a proposal on my own, I’m not sure how much time would be appropriate for this proposal. It’s relatively simple.

Add Array.asyncFrom to 2021-08 agenda

---

2021/08.md

replacing placeholder with link to slides

Change-Array-by-copy slides

---

2021/08.md

Adding Class `static` blocks for Stage 4 (pending editor review) and RegExp Feature Parity for Stage 1.

Add topics

---

2021/08.md

I plan to eventually add slides for the already linked summarization.

Add entry to report the Realms renaming bikeshed

---

2021/08.md

This is after the deadline, but I'm hoping people haven't done their agenda reviews in the last ~38 hours.

Add PR 2495

---

2021/08.md

Updating the class `static` block agenda item now that an editor has approved the PR.

Updated class `static` block agenda item

---

2021/08.md

We have an over-full agenda, and I'd rather leave time for others' topics.

Deleting my agenda items

---

2021/10.md

Add `Intl.DurationFormat` stage advancement to agenda

add intl durationformat to agenda

---

2021/10.md

This adds Partial Application for Stage 2 to the agenda, link to slides will follow shortly.

Adds partial application to agenda

---

2021/10.md

Add Record&Tuple update for Oct 2021 meeting

---

2021/12.md

Add Decimal update for December

---

2021/12.md

Add Decorators update to the agenda for December

---

2021/12.md

Add class brand check to agenda

Add class brand check topic to next meeting agenda

---

2021/12.md

Add slides for Decimal update

---

2021/12.md

Seems we already have too many topics in two days, let's delay it to the next meeting.

Delay `class.hasInstance()` proposal to next meeting

---

2022/01.md

There is a champion group involved within this proposal so the presenters list is limited and you might expect more champions leading this discussion.

Add contention point for Symbols as WeakMap keys

---

2022/01.md

2022-01: Add dataflow-proposal review

---

2022/01.md

Adding an open ended discussion topic about the StructuredClone abstraction effects being applied to ShadowRealms.
cc @syg

Topic: structured clone in shadowRealms

---

2022/01.md

This reverts the last commit, but manually.
I had some quick feedback on this topic that I feel it's better to hold on for now.

Remove ShadowRealms discussion

---

2022/01.md

Slides still WIP. I'll merge this PR once the slide is about to complete.
There're no new info in the slides just a summary so if you're interested, please check out https://github.com/Jack-Works/proposal-enum/discussions/2

Add slides for enum proposal

---

2022/01.md

Apologies for the belated slides. (They’re basically the same as last plenary’s.)

2022-01 Array.fromAsync slides

---

2022/03.md

Add unit conversion proposal to the meeting.

Add unit conversion proposal

---

2022/03.md

• Bikeshedding pipe operator’s topic reference (at Stage 2, no advance)
• Bikeshedding bind-this syntax (at Stage 1, no advance)
• Function.prototype.once for Stage 1
• Holistic discussion of TC39 dataflow proposals

2022-03: Add JSC items

---

2022/03.md

- Timebox moved from 10 to 30 minutes
- Normative changes: from 1 to 3 reported in the update
- Stage 3 Implementation and Integration updates

Update ShadowRealms updates with slides

---

2022/03.md

@ljharb I'm not sure where this entry should be in, but this PR gives the option to fix it (or not).

Move ShadowRealms entry to proposals table

---

2022/03.md

My sincere apologies, but my primary occupation has given me a constraint on Monday (1:00 PM EDT–2:30 PM EDT). Hopefully this will be able to be accommodated; if any of my agenda items cannot be at any other time, then I would withdraw it. Apologies again.

2022-03: JSC constraints

---

2022/03.md

No changes are needed for the current drafted schedule.

Add time limit of Jack Works

---

2022/03.md

I lost write access to the previous link, sigh

update extending-builtins slides

---

2022/06.md

Need to discuss with champion group who is going to present.
Stage 2 spec review has not finished. Added on the assumption that this will be complete before plenary.

adding symbols as weakmap keys for stage 3

---

2022/06.md

June 2022 Agenda Item - `findLast`/`findLastIndex` for Stage 4

---

2022/06.md

PR: https://github.com/tc39/ecma262/pull/2781
cc @gibson042

Add needs-consensus PR for time zone

---

2022/06.md

Taking another run at Atomic Operators

Adds entry for RegExp Atomic Operators

---

2022/06.md

It seems the agenda do not have enough topics , so I add two proposals for discussion. I will add materials ASAP, but may not meet the deadline.

Add two stage 0 proposal

---

2022/06.md

I've put this down as a 60 minute item, to include time for a full update and to ensure we get enough feedback in order to progress, but if there is a lack of time we could possibly make it 45 mins as well.

Add import reflection status update agenda item

---

2022/06.md

cc @ljharb I think it got messed up in the rebase

Fix decorators slides link

---

2022/06.md

Add Test262 update slides

---

2022/06.md

I am assuming DanielR wants to present given he added this.

Fix rendering of findLast/findLastIndex

---

2022/06.md

(I realize the Intl.DurationFormat is is unlikely to ask for normative changes so will be unaffected)

Mark late items

---

2022/06.md

The champions group need more time to sync this up, so we are removing this topic to be covered in the next TC39 meeting.

Removing/postponing ShadowRealms HTML Integration

---

2022/06.md

The meeting drained me of energy. Postpone it to next meeting so I (and everyone) can go to sleep early today 😩

Remove fatal error topic

---

2022/07.md

Tentatively proposing a long discussion of compartments as module loaders, at stage 1 with hopes and ambitions to be ready to request advancement.

Compartments as Module loaders 90min

---

2022/07.md

/cc @rricard @acutmore @rickbutton I believe this was added to the incorrect section. Please confirm.

move record & tuple update to correct section

---

2022/07.md

Add ShadowRealm updates to the agenda

---

2022/07.md

Adds link to current R/T slides and issues.

Add slides for Record and Tuple update July 2022

---

2022/07.md

2022-07: Function.pipe/flow, Math between, popcount

---

2022/07.md

No slides now, but I might add some before the meeting.

Add a couple needs-consensus items

---

2022/07.md

Adding `Object.{pick,omit} ` to the agenda for Stage 1/2.

Object.{pick,omit} 

---

2022/07.md

Add discussion of well-formatted PDF specs

2022.07: Add discussion of well-formatted PDF specs

---

2022/07.md

ref:  https://github.com/tc39/Reflector/issues/440

September plenary is marked as fully remote

---

2022/07.md

Add discussion item for "Clarify the layering relationship between ECMA-262 and ECMA-402"

---

2022/09.md

Ref:  https://github.com/tc39/Reflector/issues/444#issuecomment-1228363201

Add November 2022 meeting

---

2022/09.md

Didn't link the proposal repo 'cause it's stale and I don't have write access.

Add set methods agenda item

---

2022/09.md

To discuss https://github.com/tc39/proposal-string-dedent/pull/60

String.dedent discussion

---

2022/09.md

Mostly informative and editorial updates, including browser implementation and HTML integration status.

Add ShadowRealm updates

---

2022/11.md

Add 2/4 Module topics to A Coruña agenda

---

2022/11.md

cf. https://github.com/tc39/proposal-temporal/issues/2169

Add ECMA-402 scope discussion

---

2022/11.md

Source:  https://github.com/tc39/Reflector/issues/453

Add future meeting dates

---

2023/01.md

ref: https://github.com/tc39/Reflector/issues/453#issuecomment-1340542815

Defer Jan 2023 meeting by one week

---

2023/01.md

to match 10 am est 30th jan 2023

Update link for the submission deadline

---

2023/01.md

Thanks to @rbuckton for noticing

Fix 10 day deadline for January meeting

---

2023/01.md

Also removing an errant checkmark

Symbol as WeakMap key for Stage 4

---

2023/01.md

Also adding link to spec for symbols as weakmap keys. Will add spec link for Change Array by copy very soon.

Add change-array-by-copy for Stage 4

---

2023/01.md

Adds link to spec PR for change array by copy

adds spec link for change-array-by-copy

---

2023/03.md

Thought I'd get this one in now. Would be great if timings can work out for modules agenda items, but as permits of course.

Schedule constraint for March

---

2023/03.md

https://github.com/tc39/proposal-iterator-helpers/pull/265

add sync iterator helpers normative tweak item

---

2023/03.md

Adds agenda topics for Async Explicit Resource Management for stage 3 and Class Method Parameter decorators for stage 1.

Add agenda topics

---

2023/03.md

Adds more normative updates to the Decorators proposal, and combines them all into a single discussion topic as they are all relatively minor.

Add more normative updates to Decorators and coalesce into a single topic

---

2023/03.md

Add slides for class method parameter decorators proposal.

Add slides for class method parameter decorators

---

2023/03.md

See: https://github.com/tc39/Reflector/issues/456

Add Chair Group Election

---

2023/03.md

cc @michaelficarra
I haven't discussed this with the champions, but I wanted to get this up as early as possible so people could review.

add item for renaming iterator take

---

2023/03.md

Add test262 item

---

2023/03.md

Add time constrain

---

2023/03.md

If time permits at the end of the meeting, I'd like to get a feeling from the rest of the committee on nanoseconds precision for Temporal and the prospect of 96-bit storage for Temporal.Instant and Temporal.ZonedDateTime.

Add overflow item for Temporal

---

2023/05.md

Discuss Array.prototype.group

---

2023/05.md

It's fair to consider these items late, as I didn't provide presentation materials in time.

Add group and source map

---

2023/03.md

ref: https://github.com/tc39/Reflector/issues/472

Add agenda item for ES2023 vote

---

2023/05.md

Also, request additional time. There was a fair amount of interest in talking about Decimal at the last plenary; many items in the queue got dropped.

Decimal: Update title to match slide deck

---

2023/05.md

Adds some slides to help summarize/clarify the ongoing discussion

Add slides for decorator initializer order discussion

---

2023/05.md

I'm afraid I'm rather sick and can't present today as planned. Sorry about that. Looking forward to continuing the discussion in Bergen.

Remove JMN's open-ended decimal discussion

---

2023/07.md

Give that we reached conditional consensus on import attributes and that Stage 3 kicks in automatically once the conditions are fulfilled, I prefer to explicitly presents the changes happened after the March meeting.
cc @ljharb heads up in case you want to update your schedule constraint, since you were one of the reviewers

2023.07: Import attributes updates

---

2023/07.md

Sorry, I didn't know it was standard procedure when I added the slides!

Adding my name to the TG4 presentation as presenter

---

2023/07.md

Add Slides for WebAssembly

---

2023/09.md

Literals must come after operators

Add slides for operators, literals

---

2023/09.md

CC @gibson042 
Added it with an hourglass.

Add ECMA-402 PR 788

---

2023/09.md

Add ECMA-402 PR #780

---

2023/09.md
template.md

Add gantt chart to template

---

2023/09.md
template.md

https://github.com/tc39/Reflector/issues/460

Notes disclaimer

---

2023/11.md

We should make a checklist for copying over the templates, given how many of these little details need to be gotten right.

link attendee information, fix date in temporal snippet

---

2023/11.md

Add "slice notation" update and "index from end" for stage 1 to the agenda of 2023-11 meeting

---

2023/11.md

Sorry for not adding these before the deadline.

Add withdrawal overflow topics

---

2023/11.md

add 402 PR for cash rounding option

---

2023/11.md

Update slides for Intl.DurationFormat normative PRs

2023.11: Update slides for Intl.DurationFormat normative PRs

---

2024/02.md

Add slides for _Function and Object Literal Element Decorators_.

Add slides for Function and Object Literal Element Decorators

---

2024/02.md

Split off timeboxed discussion on decorated function declaration hoisting from the function decorators proposal topic.

2024.02: Split off timeboxed discussion on decorated function declaration hoisting from the function decorators proposal topic

---

2024/02.md

This is the lowest-priority item

Scrub Stage 1 proposals

---

2024/02.md

Add TG4 slides to agenda

---

2024/04.md

Hoping this will kick off some good discussions, so requesting a 60 minute time box.

April 2024 - Adding R&T discussion

---

2024/04.md

Will update from issue link to PR link ASAP (hopefully still before the deadline).

Add RKG's topic and constraint

---

template.md

not applied to the upcoming plenary agenda to preserve git history

🔥 remove obsolete checkbox column

---

2024/04.md

Add PR link to RKG topic

---

2024/04.md

No schedule constraints for signals yet

Remove errant emoji

---

.gitignore
package.json
scripts/agenda-to-schedule.mjs

been meaning to do this for a while to save us from copypasta repetition and mistakes when making the plenary schedule

✨ add script to spit out schedule-formatted topics

---

2024/06.md

Hoping to add a long talk about our current progress with source maps as well as an open discussion on a few implementation details.

Add source maps to June 2024 agenda

---

2024/06.md

Just _a little_ bit late to the game. I blame soccer (for @robpalme football)! Let's hope, no one notices!

Adding TCQ reloaded status update

---

2024/06.md

add async iterators item

---

2024/06.md

Put in the open-ended discussion section to express my desire to deprioritize this topic as necessary

Add signals topic

---

2024/06.md

Adding overflow topic as we did not have time to come back to the deterministic collapse of Await in `await using` topic in the last plenary session.

Add `await using`

---

2024/06.md

If we have extra time, this might be more important than my other late agenda items; I'd be fine to skip those if there's only room for this one.

Proposal scrub topic

---

2024/06.md

I would like to speak to the Temporal update but have constraints on time.

Add schedule constraint for Sean Burke

---

2024/06.md

Adding late agenda item for Discard Bindings

Add Discard Bindings update or Stage 2

---

2024/06.md

Apologies for lateness. Adding them so that if nothing else they can be part of the historical record

Add slides for Smart units

---

2024/07.md

I've chatted with the proposal champion, @michaelficarra, who is happy for us to have a discussion about [this issue](https://github.com/tc39/proposal-joint-iteration/issues/27) at the upcoming plenary.

July 2024 - Add join iteration naming discussion

---

2024/07.md

See tc39/Reflector#535 for more info.

add tc39/Reflector#535 topic

---

2024/07.md

add Concurrency Control proposal for Stage 1

---

2024/07.md

Am currently anticipating a fair amount of discussion for this one, since fingerprinting can be a contentious topic. May reduce the timebox next week if feedback from relevant parties suggests less time needed.

Normative: Added note about sets of locales for web browser implementations needing to not change as a result of user behaviour

---

2024/07.md

add slides for DurationFormat PR 207 and 402 PR 908

---

2024/07.md

Doesn't affect anything currently planned in the draft schedule. Apologies for sending this late.

Schedule constraint

---

2024/07.md

Essentially a summary of the discussion on the issue/PR threads

2024.07 add fingerprinting slides

---

2024/07.md

Remembered to upload them, forgot to link them in the agenda. 🤦🏻‍♀️

Secretariat slides link

---

2024/10.md

After talking with @robpalme and some other folks, I think this should be an interesting talk introducing my JS engine and starting some discussion around ahead-of-time compilation. I will likely be attending in-person and shouldn't have any scheduling constraints.

2024.10: Add Porffor engine talk

---

2024/10.md

We intend to ask for stage advancement.

Rename decimal presentation

---

2024/10.md

It's now an update, not a stage advancement request.

Downgrade scope of decimal proposal

---

2024/10.md

Add co-presenter to decimal talk

---

2024/10.md

Ref: https://github.com/tc39/Reflector/issues/537#issuecomment-2395998174

Extend Tues & Weds to 17:30

---

2024/10.md

and apologies once more for the late add

add slides for 402 normative PRs and DurationFormat normative PR

---

2024/12.md

WinterCG -> TC-55 Briefing

---

2024/12.md

Just a drive-by noticed while doing something else

Missing backquote

---

2024/12.md

The two topics are somewhat related, and it'd be best to discuss the big picture first.
CC @ben-allen

Add Measure / Vision for numeric types schedule constraint

---

2024/12.md

This is a very late addition. But this is for stage 1 and the slides + video of previous talk were already posted before the deadline.

Added link to rough draft stabilize proposal

---

2025/02.md

Adding slides for Jesse because he is unavailable today.

2025.02: Add decimal/measure slides

---

2025/02.md

Added Consensus Discussion Item and Slides.

Update 02.md - Consensus Topic

---

2025/02.md

This looks like an open-ended discussion, not a stage 0 proposal.

Move consensus item

---

2025/02.md

I have a couple of slides at the end of @jessealama's presentation, and so @ryzokuken asked that I add myself as a co-presenter.

2025.02: Add Eemeli Aro as co-presenter for "A unified vision for measure and decimal"

---

2025/02.md

for the keen and curious
https://docs.google.com/presentation/d/1uONn7T91lfZDV4frCsxpwd1QB_pU3P7F6V2j9jEPnA8/edit?usp=sharing

2025-02 R&T slides

---

2025/04.md

This also fixes a missing `)` in the Upsert item.

2025.04: Explicit Resource Management implementer feedback

---

2025/04.md

Added three advancement placeholder entries that need links, after more work is done on the content.
Before the advancement deadline, for each I will either fill in links to good enough content, or I will remove from this agenda.

Update 04.md for three proposals

---

2025/04.md

Added `Provide a compare-by-codepoint function`.
Revised some `for-stage` texts to include all possible stopping points.

Proposal: Provide a compare-by-codepoint function

---

2025/04.md

Fix April agenda deadline (-1 day)

---

2025/04.md

May only discuss and not ask for stage 1, but would like to have the option of asking for stage 1 so entering the agenda under that goal.

2025.04: Add 'composites' for stage 1

---

2025/04.md

Slides are in progress and will be posted prior to the agenda deadline.

Add Enum Declarations to agenda

---

2025/04.md

Add the new normative PR to the agenda

Add PluralRules normative PR

---

2025/04.md

Not even sure if I should've made a PR for this but since it isn't urgent...

2025.04: clarify the 'host'

---

2025/05.md

Add Samina's proposed topic

---

2025/05.md

May as well get this on the agenda right away. (Might possibly make slides later.)

2025.05: Add Ross' needs-consensus PR

---

2025/05.md

(I may have committed something to main accidentally. Sorry, but this would overwrite that anyway.

Immutable ArrayBuffer for stage 3

---

2025/05.md

The spec needs more time to cook (tc39/proposal-bigint-math#28). I plan to present this at the following plenary.

2025-05: Remove BigInt Math

---

2025/07.md

We’re tentatively preparing to *at most* seek advancement of Module Import Hooks and new Globals to Stage 1, but likely more of a status update for the existing Stage 1 compartment proposal

Add import hook and new global

---

2025/07.md

- Add a link to the slides
- Rename from Import Bytes to Import Buffer

add slides to import buffer in 2025-07 agenda

---

2025/07.md

fix 25/07 timezones

---

2025/07.md

update presenter name to match delegates.txt for RBR

---

2025/07.md

My apologies to the chairs, but need to put in a late breaking schedule constraint due to life

Add schedule constraint for Matt Gaudet

---

2025/09.md

Note, I leave the deadline in the gantt because I don't know the correct date.

Revise meeting dates and milestones in 09.md

---

2025/09.md

2025-09: Add 'proposal-await-dictionary' topic

---

2025/09.md

Add additional schedule constraint

---

2025/09.md

Looks like this is [not uncontroversial](https://github.com/tc39/how-we-work/pull/165#pullrequestreview-3242012021).

increase timebox for kebab-case item

---

2025/09.md

Most times are flexible but these times are not

2025-09: update schedule constraints for availability

---

2025/11.md

Two relatively small proposals:
* TypedArray concatenation
* TypedArray find subsequence within

Add proposals for TypedArray discussions
